format = """
[](fg:#DA84CD bg:#DA84CD)\
$username\
[](fg:#DA84CD bg:#F38DA2)\
$os\
$directory\
[](fg:#F392B2 bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#A4BFA6)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#A4BFA6 bg:#82dad3)\
$docker_context\
[](fg:#82dad3 bg:#82B1DA)\
$time\
[ ](fg:#82B1DA)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#DA84CD"
style_root = "bg:#DA84CD"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#F392B2"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#A4BFA6"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#82B1DA"
format = '[ ♥ $time ]($style)'
